php_role:
  common:
    packages:
      - "php5-curl"
      - "php5-gd"
      - "php-pear"
      - "php5-mysql"
  extensions:
    packages:
      - "php5-redis"
      - "php5-apcu"
  fpm:
    logdir: "/var/log/php5-fpm"
    owner: "www-data"
    group: "www-data"
    service: "php5-fpm"
    packages:
      - "php5-fpm"
